### ISSUE TITLE
FATAL: role "root" does not exist with Docker

### ISSUE THREAD

**Issue by chris-aeviator** [rakam-io/rakam#110]
When bringing up the projekt with docker-compose (with the supplied `docker-compose.yml`) I will get an ongoing error `role "root" does not exist` from postgresql. I realised that my (already perfectly running) rakam setup stopped running 1 month ago and got that error when restarting it with `docker-compose restart` suddenly. It is strange, since both `rakam-api` & `rakam-db` containers have the rakam user set to `rakam`:

docker-compose.yml
```
version: '2.1'
services:
  rakam-db:
    image: postgres:10.6
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rakam
      - POSTGRES_PASSWORD=dummy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
  rakam-api:
    image: buremba/rakam
    expose:
      - 9999
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=postgres://rakam:dummy@rakam-db:5432/rakam
      - RAKAM_CONFIG_LOCK__KEY=veryLongRandomString
      - LETSENCRYPT_HOST=analytics.tools.myawesomecompany.io
      - VIRTUAL_HOST=analytics.tools.myawesomecompany.io
      - LETSENCRYPT_EMAIL=chris@myawesomecompany.io

    depends_on:
      rakam-db:
        condition: service_healthy

networks:
  default:
    external:
      name: nginx-proxy
```

only after creating the psql user & database "root" the rakam api will start
