### ISSUE TITLE
How to set custom lock key?

### ISSUE THREAD

**Issue by rafaelamorim** [rakam-io/rakam#84]
Hey guys, how's going?

First of all, thanks for this awesome tool! :)

I had some struggle getting started with Rakam due to some issues with Lock Key, where whenever iI tried to create a new project using http://app.rakam.io/ the message "Invalid Lock Key" insisted to pop-up.

With a little bit of debugging i realized that rakam was not being initiated with lock key even if we provide it properly:
```
  rakam-db:
    image: postgres:9.6.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=rakam
      - POSTGRES_PASSWORD=rakam
  rakam:
    image: buremba/rakam
    ports:
      - '9999:9999'
    environment:
      - 'RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=postgres://rakam:rakam@rakam-db:5432/rakam'
      - 'RAKAM_CONFIG_ALLOW-PROJECT-DELETION=true'
      - 'RAKAM_CONFIG_LOCK-KEY=rakam'
    links:
      - rakam-db
```

and neither using the very same command as the README.md says: 
```
docker run -d --name rakam-db -e POSTGRES_PASSWORD=dummy -e POSTGRES_USER=rakam postgres:9.6.1 && docker run --link rakam-db --name rakam -p 9999:9999 -e RAKAM_CONFIG_LOCK-KEY=mylockKey -e RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=postgres://rakam:dummy@rakam-db:5432/rakam buremba/rakam
```

so when i tried to register a new project using an empty lock key, it worked! :)

What is the correct way to set `lock-key`, `allow-project-deletion` and `company-name` configuration keys properly using env vars (during docker compose/run)?

Best :)
